export interface Product {
  id: number;
  name: string;
  price: number;
  category: string;
  rating: number;
}

export const productsData: Product[] = [
  { id: 37, name: "The Pragmatic Programmer", price: 29.99, category: "Books", rating: 5 },
  { id: 16, name: "Wilson Pro Staff Tennis Racket", price: 249.99, category: "Sports", rating: 5 },
  { id: 47, name: "Samsung Smart Refrigerator", price: 1799.99, category: "Home", rating: 5 },
  { id: 6, name: "Levi's 511 Slim Jeans", price: 59.99, category: "Clothing", rating: 4 },
  { id: 23, name: "KitchenAid Stand Mixer", price: 349.99, category: "Home", rating: 5 },
  { id: 40, name: "The 48 Laws of Power", price: 23.99, category: "Books", rating: 4 },
  { id: 29, name: "Sony PlayStation 5", price: 499.99, category: "Electronics", rating: 5 },
  { id: 33, name: "Columbia Hiking Pants", price: 69.99, category: "Clothing", rating: 4 },
  { id: 42, name: "Callaway Golf Set", price: 499.99, category: "Sports", rating: 5 },
  { id: 4, name: "Dell XPS 13 Laptop", price: 1199.99, category: "Electronics", rating: 4 },
  { id: 7, name: "Nike Air Force 1 Sneakers", price: 89.99, category: "Clothing", rating: 5 },
  { id: 35, name: "Patagonia Fleece Sweater", price: 89.99, category: "Clothing", rating: 5 },
  { id: 41, name: "Adidas Predator Football", price: 34.99, category: "Sports", rating: 5 },
  { id: 36, name: "Sapiens: A Brief History of Humankind", price: 18.99, category: "Books", rating: 5 },
  { id: 46, name: "Breville Barista Express", price: 599.99, category: "Home", rating: 5 },
  { id: 11, name: "Atomic Habits", price: 15.99, category: "Books", rating: 5 },
  { id: 48, name: "LG Front Load Washing Machine", price: 799.99, category: "Home", rating: 4 },
  { id: 26, name: "GoPro HERO11 Black", price: 399.99, category: "Electronics", rating: 5 },
  { id: 2, name: "Samsung Galaxy S23 Ultra", price: 949.99, category: "Electronics", rating: 4 },
  { id: 43, name: "Speedo Swim Goggles", price: 14.99, category: "Sports", rating: 4 },
  { id: 10, name: "The North Face Jacket", price: 129.99, category: "Clothing", rating: 5 },
  { id: 39, name: "Zero to One", price: 21.99, category: "Books", rating: 4 },
  { id: 50, name: "Haier 1.5 Ton Split AC", price: 499.99, category: "Home", rating: 4 },
  { id: 25, name: "Instant Pot Duo", price: 129.99, category: "Home", rating: 5 },
  { id: 5, name: "Apple Watch Series 9", price: 499.99, category: "Electronics", rating: 4 },
  { id: 30, name: "Microsoft Xbox Series X", price: 499.99, category: "Electronics", rating: 4 },
  { id: 20, name: "Everlast Boxing Gloves", price: 49.99, category: "Sports", rating: 4 },
  { id: 12, name: "The Subtle Art of Not Giving a F*ck", price: 12.99, category: "Books", rating: 4 },
  { id: 27, name: "Bose QuietComfort 45", price: 299.99, category: "Electronics", rating: 5 },
  { id: 32, name: "Uniqlo Ultra Light Down Jacket", price: 59.99, category: "Clothing", rating: 4 },
  { id: 17, name: "Spalding NBA Basketball", price: 29.99, category: "Sports", rating: 4 },
  { id: 28, name: "Apple MacBook Air M2", price: 1099.99, category: "Electronics", rating: 5 },
  { id: 1, name: "Apple iPhone 14 Pro", price: 999.99, category: "Electronics", rating: 5 },
  { id: 44, name: "Reebok Yoga Mat", price: 24.99, category: "Sports", rating: 4 },
  { id: 31, name: "H&M Cotton Shirt", price: 24.99, category: "Clothing", rating: 3 },
  { id: 9, name: "Puma Sports T-Shirt", price: 29.99, category: "Clothing", rating: 3 },
  { id: 34, name: "Under Armour Running Shoes", price: 99.99, category: "Clothing", rating: 5 },
  { id: 21, name: "Philips Air Fryer XXL", price: 199.99, category: "Home", rating: 5 },
  { id: 18, name: "Yonex Badminton Racket", price: 59.99, category: "Sports", rating: 4 },
  { id: 3, name: "Sony WH-1000XM5 Headphones", price: 399.99, category: "Electronics", rating: 5 },
  { id: 13, name: "The Lean Startup", price: 19.99, category: "Books", rating: 4 },
  { id: 8, name: "Adidas Originals Hoodie", price: 74.99, category: "Clothing", rating: 4 },
  { id: 14, name: "Clean Code", price: 34.99, category: "Books", rating: 5 },
  { id: 49, name: "Panasonic Microwave Oven", price: 129.99, category: "Home", rating: 4 },
  { id: 19, name: "Nike Mercurial Football Boots", price: 199.99, category: "Sports", rating: 5 },
  { id: 38, name: "Rich Dad Poor Dad", price: 14.99, category: "Books", rating: 4 },
  { id: 45, name: "Mizuno Running Shorts", price: 34.99, category: "Sports", rating: 4 },
  { id: 15, name: "Deep Work", price: 16.99, category: "Books", rating: 4 },
  { id: 24, name: "Nespresso Vertuo Coffee Maker", price: 179.99, category: "Home", rating: 4 },
  { id: 22, name: "Dyson V15 Detect Vacuum", price: 699.99, category: "Home", rating: 5 },
];
